name: Deploy Documentation

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'src/pages/**'
      - 'README.md'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install Dependencies
        run: |
          cd docs
          npm ci
          npm run build
      
      - name: Sync Documentation
        run: |
          cd ..
          pwsh -File ./scripts/sync-docs.ps1
          cd docs
          npm run build
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/build
          branch: gh-pages
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
          single-commit: true
